// packages/vue/src/components/Canvas.vue
<script lang="ts" setup>
import { onMounted, onUnmounted } from "vue"
import { Editor } from "@postnitro-sdk/core"
import { useEditorState } from "./state"
import ResizeObserver from "resize-observer-polyfill"

interface Shadow {
  offsetX: number
  offsetY: number
  blur: number
  color: string
}

interface Config {
  background?: string
  shadow?: Shadow
  clipToFrame?: boolean
  frameMargin?: number
}

let container: HTMLDivElement
let resizeObserver: ResizeObserver

const editorState = useEditorState()
const { config = {} } = defineProps<{ config: Config }>()

onMounted(() => {
  container = document.getElementById("editor-container") as HTMLDivElement
  const { clientHeight, clientWidth } = container

  const editor = new Editor({
    id: "layerhub_io_canvas",
    // @ts-ignore
    state: {
      setActiveObject: (o) => {
        editorState.activeObject = o
      },
      setContextMenuRequest: (o) => {
        editorState.contextMenuRequest = o
      },
      setZoomRatio: (o) => {
        editorState.zoomRatio = o
      },
      setObjects: (o) => {
        editorState.objects = o
      },
      setEditor: (o) => {
        editorState.editor = o
      },
      setFrame: (o) => {
        editorState.frame = o
      },
    },
    config: {
      ...config,
      size: {
        width: clientWidth,
        height: clientHeight,
      },
    },
  })

  resizeObserver = new ResizeObserver((entries) => {
    const { width = clientWidth, height = clientHeight } = (entries[0] && entries[0].contentRect) || {}
    editor.canvas.resize({
      width,
      height,
    })
  })
})

onUnmounted(() => {
  if (resizeObserver && container) {
    if (container) {
      resizeObserver.unobserve(container)
    }
  }
})
</script>
<template>
  <div id="editor-container" style="flex: 1; position: relative">
    <div style="position: absolute; width: 100%; height: 100%; overflow: hidden">
      <canvas id="layerhub_io_canvas"></canvas>
    </div>
  </div>
</template>

// packages/react/src/canvas.tsx
import * as React from "react"
import { Editor } from "@postnitro-sdk/core"
import { Context } from "./context"
import ResizeObserver from "resize-observer-polyfill"
import { EditorConfig } from "@postnitro-sdk/types"

interface Props {
  config?: Partial<EditorConfig>
}
export const Canvas = (props: Props) => {
  const context = React.useContext(Context)
  const containerRef = React.useRef<HTMLDivElement>(null)

  React.useEffect(() => {
    const container = containerRef.current as HTMLDivElement
    const { clientHeight, clientWidth } = container
    const editor = new Editor({
      id: "layerhub_io_canvas",
      config: {
        ...props.config,
        size: {
          width: clientWidth,
          height: clientHeight,
        },
      },
      state: context,
    })

    const resizeObserver = new ResizeObserver((entries) => {
      const { width = clientWidth, height = clientHeight } = (entries[0] && entries[0].contentRect) || {}
      editor.canvas.resize({
        width,
        height,
      })
    })
    resizeObserver.observe(container)
    return () => {
      editor.destroy()
      if (container) {
        resizeObserver.unobserve(container)
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  return (
    <div
      id="layerhub_io_canvas_container"
      ref={containerRef}
      style={{ flex: 1, position: "relative", overflow: "hidden" }}
    >
      <div
        style={{
          position: "absolute",
          height: "100%",
          width: "100%",
        }}
      >
        <canvas id="layerhub_io_canvas"></canvas>
      </div>
    </div>
  )
}
